### ISSUE TITLE
Implement automatic configuration of a service account specific to a bucket

### ISSUE THREAD

**Issue by Alveel** [Alveel/minio-manager#3]
Implement automatic configuration of a service account specific to a bucket.

Currently, this is done in a bit of a convoluted way:

```yaml
buckets:
  - name: infra-test-bucket-1

service_accounts:
  - name: infra-test-bucket-1
    bucket: infra-test-bucket-1
```

Having the ability to do this with one line in the same resource configuration would be a significantly better user experience.
