### ISSUE TITLE
Handle service account names longer than 32 characters

### ISSUE THREAD

**Issue by Alveel** [Alveel/minio-manager#35]
A service account name may only be 32 characters long, which is easy to reach.

Handle it and put the overflow into the service account description.

**Comment by Alveel** [comment]
Turns out the handling, though improved in the secret backend, is still not completely bug-free.

Take the following example:

```yaml
service_accounts:
  - name: account-name-prefix-length-maxim
  - name: account-name-prefix-length-maximus
```

The first is OK, but the second will conflict with the first.
